export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  OWNER: 'OWNER',
  AGENT: 'AGENT',
  DEVELOPER: 'DEVELOPER',
  USER: 'USER',
};

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN];
export const PROPERTY_CREATOR_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.OWNER,
  ROLES.AGENT,
  ROLES.DEVELOPER,
];

export default ROLES;
